<?php

namespace app\entities;

use Yii;


/**
 * This is the model class for table "aplication".
 *
 * @property int $id
 * @property string $title
 * @property string $content
 * @property int $create_at
 * @property int $user_aplication
 * @property int $user_request
 */
class Aplication extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'aplication';
    }



    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['create_at', 'user_aplication', 'user_request'], 'integer'],
            [['title'], 'string', 'max' => 255],
            [['content'], 'string', 'max' => 610],
        ];
    }

    public function beforeSave($insert)
    {
        $this->user_aplication=Yii::$app->user->identity->id;
        $this->create_at=time();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'content' => 'Content',
            'create_at' => 'Create At',
            'user_aplication' => 'User Aplication',
            'user_request' => 'User Request',
        ];
    }

    public function getUser(){
        return $this->hasOne(User::className(),['id'=>'user_id']);
    }

    public function getComment(){
        return $this->hasMany(CommentAplication::className(),['id_aplication'=>'id']);
    }
}
