<?php

namespace app\entities;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
/**
 * This is the model class for table "comment_aplication".
 *
 * @property int $id
 * @property int $user_id
 * @property int $id_aplication
 * @property string $title
 * @property string $comment
 * @property string $create_at
 */
class CommentAplication extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'comment_aplication';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'create_at',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    public function beforeSave($insert)
    {
        $this->user_id=Yii::$app->user->identity->id;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_aplication'], 'required'],
            [['user_id', 'id_aplication'], 'integer'],
            [['create_at'], 'safe'],
            [['title'], 'string', 'max' => 255],
            [['comment'], 'string', 'max' => 610],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'id_aplication' => 'Id Aplication',
            'title' => 'Title',
            'comment' => 'Comment',
            'create_at' => 'Create At',
        ];
    }

    public function getAplication(){
        return $this->hasOne(Aplication::className(),['id'=>'id_aplication']);
    }

    public function getUser(){
        return $this->hasOne(User::className(),['id'=>'user_id']);
    }
}
